### ISSUE TITLE
Server-side Encryption - Call to a member function `getPath()` on null

### ISSUE THREAD

**Issue by solracsf** [nextcloud/sharelisting#284]
Not documented, but it seems that this app in not compatible with Nextcloud server-side encryption.

```
/.occ sharing:list
An unhandled exception has been thrown:
Error: Call to a member function getPath() on null in /lib/private/Files/Filesystem.php:901

Stack trace:
#0 /lib/private/Encryption/Update.php(105): OC\Files\Filesystem::getPath(47106057)
#1 /lib/private/Encryption/HookManager.php(39): OC\Encryption\Update->postUnshared(Array)
#2 /lib/private/legacy/hook.php(111): OC\Encryption\HookManager::postUnshared(Array)
#3 /lib/private/Share20/LegacyHooks.php(84): OC_Hook::emit('OCP\\Share', 'post_unshare', Array)
#4 /3rdparty/symfony/event-dispatcher/EventDispatcher.php(260): OC\Share20\LegacyHooks->postUnshare(Object(Symfony\Component\EventDispatcher\GenericEvent), 'OCP\\Share::post...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#5 /3rdparty/symfony/event-dispatcher/EventDispatcher.php(235): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'OCP\\Share::post...', Object(Symfony\Component\EventDispatcher\GenericEvent))
#6 /3rdparty/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, 'OCP\\Share::post...', Object(Symfony\Component\EventDispatcher\GenericEvent))
#7 /lib/private/EventDispatcher/SymfonyAdapter.php(70): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(Symfony\Component\EventDispatcher\GenericEvent), Object(Symfony\Component\EventDispatcher\GenericEvent))
#8 /lib/private/Share20/Manager.php(1173): OC\EventDispatcher\SymfonyAdapter->dispatch('OCP\\Share::post...', Object(Symfony\Component\EventDispatcher\GenericEvent))
#9 /lib/private/Share20/Manager.php(1481): OC\Share20\Manager->deleteShare(Object(OC\Share20\Share))
#10 /lib/private/Share20/Manager.php(1277): OC\Share20\Manager->checkExpireDate(Object(OC\Share20\Share))
#11 /apps/sharelisting/lib/Service/SharesList.php(204): OC\Share20\Manager->getSharesBy('GroupAlixia', 3, NULL, true, -1, 0)
#12 /apps/sharelisting/vendor/nikic/iter/src/iter.php(204): OCA\ShareListing\Service\SharesList->getShares('GroupAlixia')
#13 /apps/sharelisting/vendor/nikic/iter/src/iter.php(80): iter\filter(Object(Closure), Object(Generator))
#14 /apps/sharelisting/lib/Command/ListShares.php(107): iter\map(Object(Closure), Object(Generator))
#15 /lib/private/User/Manager.php(562): OCA\ShareListing\Command\ListShares->OCA\ShareListing\Command\{closure}(Object(OC\User\User))
#16 /apps/sharelisting/lib/Command/ListShares.php(110): OC\User\Manager->callForSeenUsers(Object(Closure))
#17 /3rdparty/symfony/console/Command/Command.php(255): OCA\ShareListing\Command\ListShares->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /3rdparty/symfony/console/Application.php(915): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /3rdparty/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(OCA\ShareListing\Command\ListShares), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /lib/private/Console/Application.php(214): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /console.php(99): OC\Console\Application->run()
#23 /occ(11): require_once('/var/www/nextcl...')
#24 {main}
```

**Comment by CarlSchwan** [comment]
Should probably be fixed with https://github.com/nextcloud/server/pull/31771
